Basic If-Else Statements:

1. Write a Python program to check if a given number is positive or negative.

In [4]:
n = int(input())

if n > 0:
    print("positive")
elif n == 0:
    print("Zero")
else:
    print("Negative")

 2


positive


2. Create a program that determines if a person is eligible to vote based on their age.

In [8]:
persons_age = int(input("Enter the age: "))

if persons_age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter the age:  17


You are not eligible to vote


3. Develop a program to find the maximum of two numbers using if-else statements.

In [9]:
n1 = 10
n2 = 20

if n1 > n2:
    print(n1)
else:
    print(n2)

20


4. Write a Python script to classify a given year as a leap year or not.

In [10]:
year = 200

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print(f"{year} is a leap year")

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print(f"{year} is a leap year")

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print(f"{year} is not a leap year")

200 is not a leap year


5. Create a program that checks whether a character is a vowel or a consonant.

In [11]:
char = 'a'

if (char == 'a') or (char == 'e') or (char == 'i') or (char == 'o') or (char == 'u'):
    print("It is a vowel")
else:
    print("It's not a vowel")

It is a vowel


6. Implement a program to determine whether a given number is even or odd.

In [16]:
n = 10

if n % 2 == 0:
    print("Even")
elif n == 0:
    print("Zero")
else:
    print("Odd")

Even


7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

In [18]:
def abs_value(n):
    if n < 0:
        return -n
    else:
        return n
abs_value(-10)
    

10

8. Develop a program that determines the largest of three given numbers using if-else statements.

In [19]:
n1 = 10
n2 = 20
n3 = 30

if (n1 > n2) and (n1 > n3):
    print(f"{n1} is the largest of the three")
elif (n2 > n1) and (n2 > n3):
     print(f"{n2} is the largest of the three")
else:
    print(f"{n3} is the largest of the three")

30 is the largest of the three


9. Create a program that checks if a given string is a palindrome.

In [22]:
string = '121'

if string == string[::-1]:
    print("It is a palindrome")
else:
      print("It is not a palindrome")

It is a palindrome


10. Write a Python program to calculate the grade based on a student's score.

In [2]:
score = 80

if score >= 80:
    print("A Grade")
elif score >= 60:
    print("B Grade")
elif score >= 35:
    print("C Grade")
else:
    print("Fail")

A Grade


Nested If-Else Statements:

11. Write a program to find the largest among three numbers using nested if-else statements.

In [29]:
n1 = 10
n2 = 20
n3 = 30

if (n1 > n2) and (n1 > n3):
    print(f"{n1} is the largest of the three")
    if (n2 > n1) and (n2 > n3):
        print(f"{n2} is the largest of the three")
else:
    print(f"{n3} is the largest of the three")

30 is the largest of the three


12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [46]:
a = 30
b = 20
c = 10

if a == b == c:
    print("Equilateral")
    if (a==b!=c) or (a!=b==c) or (a==c!=b):
        print("Isosceles")
else:
    print("Scalene")

Scalene


13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [47]:
year = 2004

if (year % 100 == 0) and (year % 400 == 0):
    print("leap year & century year")
    if (year % 100 !=0) and (year % 4 == 0):
        print("leap year but not century year")
else:
    print("Not a leap year and Not a century year")

Not a leap year and Not a century year


14. Write a Python script to determine if a number is positive, negative, or zero.

In [48]:
n = int(input())

if n > 0:
    print("positive")
    if n == 0:
        print("Zero")
else:
    print("Negative")

 10


positive


15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [49]:
age = 20

if (age >= 13) and (age < 19):
    print("Teenager")
    if age <13:
        print("Below teenager")
else:
    print("Above teenager")

Above teenager


16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

In [51]:
angle_in_degree = 90

if angle_in_degree < 90:
    print("Acute angle")
    if angle_in_degree  == 90:
        print("Right angle")
else:
    print("Obtuse Angle")


Obtuse Angle


17. Write a Python program to calculate the roots of a quadratic equation.

In [52]:
#ax**2 + bx + c = 0
import cmath
a = 1
b = 5
c = 6
# calculate the discriminant
d = (b**2) - (4*a*c)
# find two solutions
sol1 = (-b-cmath.sqrt(d))/(2*a)
sol2 = (-b+cmath.sqrt(d))/(2*a)

print('The solution are {0} and {1}'.format(sol1,sol2))

The solution are (-3+0j) and (-2+0j)


18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
for Tuesday, etc.).

In [65]:
Day = input("Enter the Day: ").lower()

if Day == 'monday':
    print("1")
    if Day =='tuesday':
        print("2")
        if Day =='wednesday':
            print("3")
            if Day =='thursday':
                print("4")
                if Day =='friday':
                    print("5")
                    if Day =='saturday':
                        print("6")
else:
    print("7")

Enter the Day:  MoNdaY


1


19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

In [67]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(f"{year} is a leap year.")
else:
    print(f"{year} is not a leap year.")


Enter a year:  200


200 is not a leap year.


20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [73]:
n = 20

if n == 0 or n == 1:
    print("Non-Prime Numbers")
elif n == 2:
    print("Prime")
else:
    is_prime = True
    for i in range(2, n):
        if n % i == 0:
            is_prime = False
            break
    if is_prime:
        print("Prime")
    else:
        print("Non-Prime")


Non-Prime


Elif Statements:

21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [3]:
score = 80

if score >= 80:
    print("A Grade")
elif score >= 60:
    print("B Grade")
elif score >= 35:
    print("C Grade")
else:
    print("Fail")

A Grade


22. Implement a program to determine the type of a triangle based on its angles.

In [5]:
angle_in_degree = 90

if angle_in_degree < 90:
    print("Acute angle")
elif angle_in_degree  == 90:
    print("Right angle")
else:
    print("Obtuse Angle")

Right angle


23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
elif statements.

In [6]:
BMI = 20

if BMI >= 21 and BMI <=25 :
    print("Normal")
elif BMI >25:
    print("Overweigth")
else:
    print("Underweight")

Underweight


24. Create a program that determines whether a given number is positive, negative, or zero using elif
statements.

In [7]:
n = int(input())

if n > 0:
    print("positive")
elif n == 0:
    print("Zero")
else:
    print("Negative")

 100


positive


25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
statements.

In [14]:
string ='SAIKUMAR'

if string.isupper:
    print("Upper")
elif string.islower:
    print("Lower")
elif not string.isalnum:
    print("special")
else:
    print("None of the above")

Upper


26. Implement a program to calculate the discounted price based on different purchase amounts using elif
statements.

In [16]:
Purchase_Price = 100

if Purchase_Price >= 100:
    #Discount=10%
    Price = 100*(1 - 0.1)
    print(Price)
elif Purchase_Price >=80:
    #Discount=6%
    Price = 100*(1 - 0.06)
else:
    Price(Purchase_Price)
    

90.0


27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
statements.

In [23]:
Units = 100

if Units >= 100:
    unit_price = 10
    Total_Price = Units * unit_price
    print(Total_Price)
elif Units >=80:
    Unit_price = 12
    Total_Price = Units * unit_price
    print(Total_Price)
else:
    Total_Price = Units * 15
    print(Total_Price)

1000


28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
statements.

In [24]:
# Input the lengths of the four sides
side1 = float(input("Enter the length of the first side: "))
side2 = float(input("Enter the length of the second side: "))
side3 = float(input("Enter the length of the third side: "))
side4 = float(input("Enter the length of the fourth side: "))

# Input the measures of the four angles
angle1 = float(input("Enter the measure of the first angle in degrees: "))
angle2 = float(input("Enter the measure of the second angle in degrees: "))
angle3 = float(input("Enter the measure of the third angle in degrees: "))
angle4 = float(input("Enter the measure of the fourth angle in degrees: "))

# Check for the type of quadrilateral using elif statements
if angle1 == angle2 == angle3 == angle4 == 90:
    if side1 == side2 == side3 == side4:
        print("It is a square.")
    else:
        print("It is a rectangle.")
elif side1 == side3 and side2 == side4:
    print("It is a trapezoid.")
else:
    print("It is a general quadrilateral.")

Enter the length of the first side:  22
Enter the length of the second side:  23
Enter the length of the third side:  33
Enter the length of the fourth side:  2
Enter the measure of the first angle in degrees:  90
Enter the measure of the second angle in degrees:  90
Enter the measure of the third angle in degrees:  90
Enter the measure of the fourth angle in degrees:  78


It is a general quadrilateral.


In [27]:
# Input a month from the user
month = input("Enter a month (e.g., January, February, etc.): ").lower()

# Define the seasons and their respective months
spring_months = ["march", "april", "may"]
summer_months = ["june", "july", "august"]
fall_months = ["september", "october", "november"]
winter_months = ["december", "january", "february"]

# Check the input month and determine the season
if month in spring_months:
    print(f"{month.capitalize()} is in the spring season.")
elif month in summer_months:
    print(f"{month.capitalize()} is in the summer season.")
elif month in fall_months:
    print(f"{month.capitalize()} is in the fall season.")
elif month in winter_months:
    print(f"{month.capitalize()} is in the winter season.")
else:
    print("Invalid input. Please enter a valid month.")

Enter a month (e.g., January, February, etc.):  January


January is in the winter season.


30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
elif statements.

In [30]:
# Input a year from the user
year = int(input("Enter a year: "))

# Input a month from the user
month = input("Enter a month (e.g., January, February, etc.): ").lower()

# Determine if it's a leap year
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    is_leap_year = True
else:
    is_leap_year = False

# Use elif statements to determine the number of days in the month
if month in ["january", "march", "may", "july", "august", "october", "december"]:
    days_in_month = 31
elif month in ["april", "june", "september", "november"]:
    days_in_month = 30
elif month == "february":
    if is_leap_year:
        days_in_month = 29
    else:
        days_in_month = 28
else:
    print("Invalid input for month.")
    days_in_month = None

# Print the results
if days_in_month is not None:
    if is_leap_year:
        print(f"{year} is a leap year.")
    else:
        print(f"{year} is a common year.")
    print(f"{month.capitalize()} has {days_in_month} days.")

Enter a year:  222
Enter a month (e.g., January, February, etc.):  ddd


Invalid input for month.


31. Create a program that validates a password based on complexity rules (length, characters, etc.).

In [31]:
import re

def valid_password(password):
    if len(password) < 8:
        return False
    if not any(char.isupper() for char in password):
        return False
    if not any(char.islower() for char in password):
        return False
    if not any(char.isdigit() for char in password):
        return False
    if not re.search(r'[!@#$%^&*(),.?":{}|<>]', password):
        return False
    return True
password = input("Enter a password: ")
if valid_password(password):
    print("Valid password")
else:
    print("Invalid password")
               

Enter a password:  2u013hvhavxv%


Invalid password


32. Develop a program that performs matrix addition and subtraction based on user input.

In [37]:
# Function to input a matrix from the user
def input_matrix(rows, cols):
    matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            element = int(input(f"Enter element at row {i + 1}, column {j + 1}: "))
            row.append(element)
        matrix.append(row)
    return matrix

# Input the dimensions of the matrices
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of columns: "))

# Input the first matrix
print("Enter elements of the first matrix:")
matrix1 = input_matrix(rows, cols)

# Input the second matrix
print("Enter elements of the second matrix:")
matrix2 = input_matrix(rows, cols)

# Printing elements of matrix1
print("Printing elements of first matrix:")
for row in matrix1:
    for element in row:
        print(element, end=" ")
    print()

# Printing elements of matrix2
print("Printing elements of second matrix:")
for row in matrix2:
    for element in row:
        print(element, end=" ")
    print()

# Subtracting two matrices
result = [[0 for i in range(cols)] for i in range(rows)]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] - matrix2[i][j]

# Printing the result
print("Subtraction of two matrices:")
for row in result:
    for element in row:
        print(element, end=" ")
    print()
    
# adding two matrices
result = [[0 for i in range(cols)] for i in range(rows)]
for i in range(len(matrix1)):
    for j in range(len(matrix1[0])):
        result[i][j] = matrix1[i][j] + matrix2[i][j]

# Printing the result
print("Addition of two matrices:")
for row in result:
    for element in row:
        print(element, end=" ")
    print()

Enter the number of rows:  1
Enter the number of columns:  1


Enter elements of the first matrix:


Enter element at row 1, column 1:  1


Enter elements of the second matrix:


Enter element at row 1, column 1:  1


Printing elements of first matrix:
1 
Printing elements of second matrix:
1 
Subtraction of two matrices:
0 
Addition of two matrices:
2 


33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
algorithm.

In [38]:
# Function to calculate the GCD using the Euclidean algorithm
def euclidean_gcd(a, b):
    while b:
        a, b = b, a % b
    return a

# Input two numbers from the user
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

# Calculate the GCD using the Euclidean algorithm
gcd = euclidean_gcd(num1, num2)

# Display the result
print(f"The GCD of {num1} and {num2} is {gcd}")

Enter the first number:  22
Enter the second number:  34


The GCD of 22 and 34 is 2


In [1]:
def input_matrix(rows, cols):
    matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element at row {i + 1}, column {j + 1}: "))
            row.append(element)
        matrix.append(row)
    return matrix

# Function to print a matrix
def print_matrix(matrix):
    for row in matrix:
        for element in row:
            print(element, end=" ")
        print()

# Function to perform matrix multiplication
def multiply_matrices(matrix1, matrix2):
    # Check if matrices can be multiplied
    if len(matrix1[0]) != len(matrix2):
        return None

    # Initialize the result matrix with zeros
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            row.append(0)
        result.append(row)

    # Perform matrix multiplication
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]

    return result

# Input the dimensions of the first matrix
rows1 = int(input("Enter the number of rows for the first matrix: "))
cols1 = int(input("Enter the number of columns for the first matrix: "))

# Input the dimensions of the second matrix
rows2 = int(input("Enter the number of rows for the second matrix: "))
cols2 = int(input("Enter the number of columns for the second matrix: "))

# Input the first matrix
print("Enter elements of the first matrix:")
matrix1 = input_matrix(rows1, cols1)

# Input the second matrix
print("Enter elements of the second matrix:")
matrix2 = input_matrix(rows2, cols2)

# Perform matrix multiplication
result = multiply_matrices(matrix1, matrix2)

# Print the results
if result is not None:
    print("\nMatrix 1:")
    print_matrix(matrix1)

    print("\nMatrix 2:")
    print_matrix(matrix2)

    print("\nMatrix Multiplication Result:")
    print_matrix(result)
else:
    print("Matrix multiplication is not possible due to incompatible dimensions.")

Enter the number of rows for the first matrix:  2
Enter the number of columns for the first matrix:  2
Enter the number of rows for the second matrix:  2
Enter the number of columns for the second matrix:  2


Enter elements of the first matrix:


Enter element at row 1, column 1:  2
Enter element at row 1, column 2:  2
Enter element at row 2, column 1:  2
Enter element at row 2, column 2:  2


Enter elements of the second matrix:


Enter element at row 1, column 1:  23
Enter element at row 1, column 2:  23
Enter element at row 2, column 1:  23
Enter element at row 2, column 2:  23



Matrix 1:
2.0	2.0	
2.0	2.0	

Matrix 2:
23.0	23.0	
23.0	23.0	

Matrix Multiplication Result:
92.0	92.0	
92.0	92.0	


35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.

In [1]:
# Tic-Tac-Toe Program using
# random number in Python

# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board
def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board
def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player
def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)
# Checks whether the player has three
# of their marks in a horizontal row
def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row
def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [1 0 0]]
Board after 2 move
[[0 0 0]
 [0 0 0]
 [1 2 0]]
Board after 3 move
[[0 0 0]
 [0 0 1]
 [1 2 0]]
Board after 4 move
[[0 2 0]
 [0 0 1]
 [1 2 0]]
Board after 5 move
[[0 2 0]
 [1 0 1]
 [1 2 0]]
Board after 6 move
[[0 2 0]
 [1 2 1]
 [1 2 0]]
Winner is: 2


36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

In [6]:
x = 0
y = 1

print(x)
print(y)

for i in range(10):
    z = x + y
    x = y
    y = z
    print(z)

0
1
1
2
3
5
8
13
21
34
55
89


37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

In [8]:
x = 0
y = 1

# Input the value of n
n = int(input("Enter the value of n: "))

for i in range(n - 1):
    z = x + y
    x = y
    y = z

print(f"The {n}th Fibonacci number is {z}")

Enter the value of n:  10


The 10th Fibonacci number is 55


38. Create a program that generates a calendar for a given month and year using conditional statements.

In [9]:
import calendar

# Input month and year
year = int(input("Enter the year: "))
month = int(input("Enter the month (1-12): "))

# Validate input
if month < 1 or month > 12:
    print("Invalid month. Please enter a month between 1 and 12.")
else:
    # Create a calendar object for the specified month and year
    cal = calendar.month(year, month)

    # Print the calendar
    print(f"Calendar for {calendar.month_name[month]} {year}:\n")
    print(cal)

Enter the year:  2023
Enter the month (1-12):  9


Calendar for September 2023:

   September 2023
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [12]:
import calendar as cl
a = cl.month(2023,9)

print(a)

   September 2023
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [15]:
import random

card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
deck = [(card, category) for category in card_categories for card in cards_list]

def card_value(card):
	if card[0] in ['Jack', 'Queen', 'King']:
		return 10
	elif card[0] == 'Ace':
		return 11
	else:
		return int(card[0])

random.shuffle(deck)
player_card = [deck.pop(), deck.pop()]
dealer_card = [deck.pop(), deck.pop()]

while True:
	player_score = sum(card_value(card) for card in player_card)
	dealer_score = sum(card_value(card) for card in dealer_card)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("\n")
	choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower()
	if choice == "play":
		new_card = deck.pop()
		player_card.append(new_card)
	elif choice == "stop":
		break
	else:
		print("Invalid choice. Please try again.")
		continue

	if player_score > 21:
		print("Cards Dealer Has:", dealer_card)
		print("Score Of The Dealer:", dealer_score)
		print("Cards Player Has:", player_card)
		print("Score Of The Player:", player_score)
		print("Dealer wins (Player Loss Because Player Score is exceeding 21)")
		break

while dealer_score < 17:
	new_card = deck.pop()
	dealer_card.append(new_card)
	dealer_score += card_value(new_card)

print("Cards Dealer Has:", dealer_card)
print("Score Of The Dealer:", dealer_score)
print("\n")

if dealer_score > 21:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)")
elif player_score > dealer_score:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Player wins (Player Has High Score than Dealer)")
elif dealer_score > player_score:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Dealer wins (Dealer Has High Score than Player)")
else:
	print("Cards Dealer Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("It's a tie.")


Cards Player Has: [('2', 'Spades'), ('10', 'Spades')]
Score Of The Player: 12




What do you want? ["play" to request another card, "stop" to stop]:  stop


Cards Dealer Has: [('Jack', 'Hearts'), ('5', 'Clubs'), ('Queen', 'Spades')]
Score Of The Dealer: 25


Cards Dealer Has: [('Jack', 'Hearts'), ('5', 'Clubs'), ('Queen', 'Spades')]
Score Of The Dealer: 25
Cards Player Has: [('2', 'Spades'), ('10', 'Spades')]
Score Of The Player: 12
Player wins (Dealer Loss Because Dealer Score is exceeding 21)


In [16]:
# Function to generate prime factors using trial division
def prime_factors(n):
    factors = []
    divisor = 2
    
    while divisor <= n:
        if n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        else:
            divisor += 1
    
    return factors

# Input the number
num = int(input("Enter a positive integer: "))

if num < 2:
    print("Prime factors are not defined for numbers less than 2.")
else:
    factors = prime_factors(num)
    
    if len(factors) == 1:
        print(f"{num} is a prime number.")
    else:
        print(f"The prime factors of {num} are: {', '.join(map(str, factors))}")

Enter a positive integer:  12


The prime factors of 12 are: 2, 2, 3
